// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-w0kZQx02FWCy0spmYuPgJFn0o827JMI',
    appId: '1:599950198358:web:2e25e3f7c1c9adc3c69df7',
    messagingSenderId: '599950198358',
    projectId: 'eccomerce-app-ossam',
    authDomain: 'eccomerce-app-ossam.firebaseapp.com',
    storageBucket: 'eccomerce-app-ossam.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7YCSUC521fqBTpQblvJj2w6Qb2LQ5q2k',
    appId: '1:599950198358:android:7c25cf49d724e6cdc69df7',
    messagingSenderId: '599950198358',
    projectId: 'eccomerce-app-ossam',
    storageBucket: 'eccomerce-app-ossam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaLYzvocfH7Zszilhh8S3qScfQWnZboT4',
    appId: '1:599950198358:ios:26bf55416a689289c69df7',
    messagingSenderId: '599950198358',
    projectId: 'eccomerce-app-ossam',
    storageBucket: 'eccomerce-app-ossam.firebasestorage.app',
    iosBundleId: 'com.example.eccomerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaLYzvocfH7Zszilhh8S3qScfQWnZboT4',
    appId: '1:599950198358:ios:26bf55416a689289c69df7',
    messagingSenderId: '599950198358',
    projectId: 'eccomerce-app-ossam',
    storageBucket: 'eccomerce-app-ossam.firebasestorage.app',
    iosBundleId: 'com.example.eccomerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-w0kZQx02FWCy0spmYuPgJFn0o827JMI',
    appId: '1:599950198358:web:98c9c7703e70a437c69df7',
    messagingSenderId: '599950198358',
    projectId: 'eccomerce-app-ossam',
    authDomain: 'eccomerce-app-ossam.firebaseapp.com',
    storageBucket: 'eccomerce-app-ossam.firebasestorage.app',
  );
}
